ARG BUILDER_IMAGE=golang:1.20-bullseye
ARG BASE_IMAGE=alpine:3.17

FROM ${BUILDER_IMAGE} AS build-stage

ENV CGO_ENABLED=0

WORKDIR /src/
COPY . .

RUN make sidekick

# Final Docker image
FROM ${BASE_IMAGE} AS final-stage
LABEL MAINTAINER "Shreyas Mishra <shreyas@accuknox.com>"

RUN apk add --update --no-cache ca-certificates

# Create user falcosidekick
RUN addgroup -S sidekick && adduser -u 1234 -S sidekick -G sidekick
# must be numeric to work with Pod Security Policies:
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups
USER 1234

WORKDIR ${HOME}/app
COPY LICENSE .
COPY --from=build-stage /src/sidekick .

EXPOSE 2801

ENTRYPOINT ["./sidekick"]
